### ISSUE TITLE
Add support for query string parameters

### ISSUE THREAD

**Issue by laurence-myers** [typepoint/typepoint#60]
Consider a "get TODOs" endpoint, where we optionally want to filter by multiple criteria, e.g. the "active" TODOs that are due this month, assigned to a specific user. For a GET endpoint, we can't pass a body, so these arguments currently need to be passed in as path parameters. This can easily lead to a combinatorial explosion of endpoints; with three optional criteria, we need these endpoints:

- Get all items
- Get all active items
- Get all items by due date
- Get all items assigned to a user
- Get all active items by due date
- Get all active items assigned to a user
- Get all items assigned to a user by due date
- Get all active items assigned to a user by due date

(You could work around it by using a POST endpoint, but it's not very RESTful.)

**Comment by codeandcats** [comment]
You can use query parameters today, you just need to specify them in endpoint definition request parameters type. No need to specify them in the path. Query parameters will be ignored for the purposes of *matching* a request to an endpoint handler, but they will still be passed to the handler in the normal request query params object.

This isn't really highlighted in the documentation and needs to be updated.

**Comment by laurence-myers** [comment]
Ah, okay. Yes, neither the docs nor examples mention query string params.

So does that mean path params and query string params need to be defined in the one type? E.g. to extend the example from the docs:

```typescript
import { defineEndpoint, Empty } from '@typepoint/shared';

export interface Todo {
  id: string;
  title: string;
  isCompleted: boolean;
}

export interface GetTodoRequestParams {
  id: string; // path param
  expanded: boolean; // query string param
}

export const getTodoEndpoint = defineEndpoint<GetTodoRequestParams, Empty, Todo[]>(path =>
  path.literal('/api/todos/').param('id'),
);
``` 

Server:
```typescript
import { createHandler } from '@typepoint/server';
import { getTodoEndpoint } from '../../shared/endpoints/getTodoHandler';
import { getTodoById } from './todoService';

export const getTodoHandler = createHandler(getTodoEndpoint, async ({ request, response }) => {
  // Get todo from our async todo service and put it in our response body
  response.body = await getTodoById(request.params.id, request.query.expanded);
});
```

**Comment by codeandcats** [comment]
> So does that mean path params and query string params need to be defined in the one type

That's correct. I couldn't think of a good reason to keep them separated and figured combining them simplifies things.

But yeah, documentation is definitely lacking on that subject. There is a separate [task](https://github.com/typepoint/typepoint.github.io/issues/10) to add it as part of a F.A.Q. page in the documentation.

We can leave this issue open as a task to add this case to the examples. I'm thinking a good use case in the example project could be:

```typescript
export interface GetTodosRequestParams {
  filter?: 'all' | 'completed' | 'incomplete';
}
```

**Comment by laurence-myers** [comment]
How does validation work for query params? I had a quick look at the source and couldn't see any validation/transformation being applied.

https://github.com/typepoint/typepoint/blob/master/packages/server/src/middlewareHelper.ts#L86

**Comment by codeandcats** [comment]
Okay, here's a summary of the flow:

1. In `@typepoint/express` there's a [`toMiddleware`](https://github.com/typepoint/typepoint/blob/a644249e8f8ddb173c509a282cfb6638688d695c/packages/express/src/index.ts#L24) function which accepts a typepoint router (which contains all the handlers) and returns an express middleware function.

2. When a request comes in, the middleware uses a [`HandlerMatchIterator`](https://github.com/typepoint/typepoint/blob/a644249e8f8ddb173c509a282cfb6638688d695c/packages/server/src/middlewareHelper.ts#L23) to find the next typepoint middleware or handler that has an endpoint definition that matches the request method & path.

3. When the `HandlerMatchIterator` returns the next handler, it also returns the parsed path parameters and query parameters. The path parameters are based on the parameters defined in the handler's endpoint definition.

4. The combined path and query parameters are [loaded into `context.request.params`](https://github.com/typepoint/typepoint/blob/a644249e8f8ddb173c509a282cfb6638688d695c/packages/express/src/index.ts#L59).

5. The request payload (parameters and body) are [then validated](https://github.com/typepoint/typepoint/blob/a644249e8f8ddb173c509a282cfb6638688d695c/packages/express/src/index.ts#L61) using the validateAndTransform function that was passed into the typepoint router constructor (unless there is no validateAndTransform function).

6. If the payload is invalid then typepoint will [respond with a http status code of 400](https://github.com/typepoint/typepoint/blob/a644249e8f8ddb173c509a282cfb6638688d695c/packages/server/src/middlewareHelper.ts#L88), otherwise it will proceed to [execute the handler](https://github.com/typepoint/typepoint/blob/a644249e8f8ddb173c509a282cfb6638688d695c/packages/express/src/index.ts#L71).

[`@typepoint/joiful`](https://www.npmjs.com/package/@typepoint/joiful) provides a [way to generate](https://github.com/typepoint/typepoint/blob/a644249e8f8ddb173c509a282cfb6638688d695c/packages/joiful/src/index.ts#L17) a validateAndTransform function that you can pass to your typepoint router, which will use [joiful](https://www.npmjs.com/package/@typepoint/joiful) to validate your typepoint request parameters based on the request parameters class associated with any given endpoint definition.

Hope that makes sense.

There's [tasks](https://github.com/orgs/typepoint/projects/1) to add documentation for validation, express, etc. Maybe I'll try to do some of that this weekend.

**Comment by laurence-myers** [comment]
Okay. Sounds like my example was incorrect, and the server code needs to look like this:

```typescript
import { createHandler } from '@typepoint/server';
import { getTodoEndpoint } from '../../shared/endpoints/getTodoHandler';
import { getTodoById } from './todoService';

export const getTodoHandler = createHandler(getTodoEndpoint, async ({ request, response }) => {
  // Get todo from our async todo service and put it in our response body
  response.body = await getTodoById(request.params.id, request.params.expanded);
});
```

Note the `request.params.expanded` instead of `request.query.expanded`.

Is the "response" still derived from the Express response, or is it a new object? If the former, I think there could be a bug if we don't delete `response.query`. A developer might accidentally read from the `response.query` object, which hasn't been validated/sanitised.

**Comment by codeandcats** [comment]
> Note the `request.params.expanded` instead of `request.query.expanded`.

Sorry I didn't notice that in your original post. Yes, it should be `request.params.expanded`.

> Is the "response" still derived from the Express response, or is it a new object?

Do you mean "request"? Both the request and response are light wrappers around express. I hope to add support for other js web frameworks too like koa and serverless via separate packages.

**Comment by laurence-myers** [comment]
Yes, sorry, I meant `request`.

I worry that merging `query` into `params` goes against being a "light wrapper"; it changes the behaviour from express, where `query` and `params` are separate concepts.

For now, probably the easiest way to avoid use of the unvalidated `request.query` would be to chuck in the statement `delete request.query`. Where do you think the best place to do this is? [The same line that we reassign `request.params`](https://github.com/typepoint/typepoint/blob/a644249e8f8ddb173c509a282cfb6638688d695c/packages/express/src/index.ts#L59) after parsing the URL?

**Comment by codeandcats** [comment]
To clarify I'm not trying to mirror the express API (you'll notice other differences) so I don't think it really matters that params and query have been merged. The goal here was to simplify the API but if it proves too confusing or if there's other good arguments against it, I'll consider splitting them out.

As for avoiding use of unvalidated `request.query` there is literally no `request.query` for a handler or middleware to get access to.

**Comment by laurence-myers** [comment]
Ah okay. I misunderstood what you meant by "Both the request and response
are light wrappers around express." I interpreted that to mean they extend
the express request/response objects, but it sounds like it exposes a
slightly different API (a subset?).

I think I'll read the code before I ask more questions. 😁

**Comment by codeandcats** [comment]
Hehe all good. Are you planning on building something with it?

**Comment by laurence-myers** [comment]
Yep, looking to use it in combination with Next.js, hopefully they play nice together. (Next.js uses "convention over configuration", so your API endpoints are defined by file names and paths, but this doesn't give you strong type-safe contracts, so the client code is very manual - string-based URLs, manual serialising/deserialising. And there's no built-in validation.)

**Comment by codeandcats** [comment]
Awesome. I had planned to add a Next.js Todo app example to the [examples repo](https://github.com/typepoint/examples) so I'd be interested to hear if you run into any problems. Maybe shoot me an email first if you do or have questions. Of-course if you felt like adding an example project yourself that'd be amazing.

**Comment by codeandcats** [comment]
@laurence-myers FYI, I just pushed up a [nextjs example](https://github.com/typepoint/examples/tree/master/todos-nextjs) if you're interested.
